---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ewm-sim-foo
  name: ewm-sim-foo
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ewm-sim-foo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ewm-sim-foo
    spec:
      containers:
      - env:
        - name: ODATA_USER
          value: {{ .Values.ewmsim.envs.ewm.user }}
        - name: ODATA_PASSWD
          value: {{ .Values.ewmsim.envs.ewm.password }}
        image: docker.io/yschiebelhut/odata-mock-server
        imagePullPolicy: Always
        name: odata-mock-server-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ewm-sim-foo
  name: ewm-sim-foo-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ewm-sim-foo
  sessionAffinity: None
  type: LoadBalancer
---